/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_appsync_graphqlEndpoint: process.env.aws_appsync_graphqlEndpoint,
  aws_appsync_region: "ap-northeast-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: process.env.aws_appsync_apiKey,
  aws_cognito_identity_pool_id: process.env.aws_cognito_identity_pool_id,
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: process.env.aws_user_pools_id,
  aws_user_pools_web_client_id: process.env.aws_user_pools_web_client_id,
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: process.env.aws_user_files_s3_bucket,
  aws_user_files_s3_bucket_region: "ap-northeast-1",
};

export default awsmobile;
