/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_appsync_graphqlEndpoint:
    "https://2b2d6auxove6blzy7andnvbq74.appsync-api.ap-northeast-1.amazonaws.com/graphql",
  aws_appsync_region: "ap-northeast-1",
  aws_appsync_authenticationType: "API_KEY",
  aws_appsync_apiKey: "da2-qfp2prl3ojf7lgxqpxfbqwp4te",
  aws_cognito_identity_pool_id: "ap-northeast-1:9bf0064a-866a-492a-94f2-eb81ac69c0d7",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_Q3szuwrwv",
  aws_user_pools_web_client_id: "2si4b5f54ehi7uekc1jp4kkaj0",
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  aws_user_files_s3_bucket: "englishmatee0e7a514d3df4b3cb14432f7761f2045153554-dev",
  aws_user_files_s3_bucket_region: "ap-northeast-1",
};

export default awsmobile;
